# Specify the modules to be included

if(NOT TARGET deltares_common)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${deltares_common_module} deltares_common)
endif()

if(NOT TARGET deltares_common_c)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${deltares_common_c_module} deltares_common_c)
endif()

if(NOT TARGET deltares_common_mpi)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${deltares_common_mpi_module} deltares_common_mpi)
endif()

if(NOT TARGET morphology_plugins_c)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${morphology_plugins_c_module} morphology_plugins_c)
endif()
if(NOT TARGET morphology_data)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${morphology_data_module} morphology_data)
endif()
if(NOT TARGET morphology_kernel)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${morphology_kernel_module} morphology_kernel)
endif()
if(NOT TARGET morphology_io)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${morphology_io_module} morphology_io)
endif()

if(NOT TARGET delftio_shm)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${delftio_shm_module} delftio_shm)
endif()
if(NOT TARGET delftio)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${delftio_module} delftio)
endif()

# Third party libraries
if(NOT TARGET kdtree2)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${kdtree_module} kdtree2)
endif()
if(NOT TARGET kdtree_wrapper)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${kdtree_wrapper_module} kdtree_wrapper)
endif()
if(NOT TARGET triangle_c)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${triangle_c_module} triangle_c)
endif()
if(NOT TARGET netcdff)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${netcdf_module} netcdff)
endif()
if(NOT TARGET io_netcdf)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${io_netcdf_module} io_netcdf)
endif()
if(NOT TARGET io_netcdf_data)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${io_netcdf_data_module} io_netcdf_data)
endif()
if(NOT TARGET fortrangis)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${fortrangis_module} fortrangis)
endif()
if(NOT TARGET shp)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${shp_module} shp)
endif()
if(WIN32)
    if(NOT TARGET proj)
        include(${CMAKE_CURRENT_SOURCE_DIR}/configurations/include/proj_configuration.cmake)
    endif()
endif(WIN32)
if(NOT TARGET ec_module)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${ec_module} ec_module)
endif()
if(NOT TARGET gridgeom)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${gridgeom_module} gridgeom)
endif()
if(NOT TARGET io_hyd)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${io_hyd_module} io_hyd)
endif()

include(${CMAKE_CURRENT_SOURCE_DIR}/configurations/include/dwaq/dwaq_base.cmake)

if(NOT TARGET nefis)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${nefis_module} nefis)
endif()
if(NOT TARGET esmfsm_version_number)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${esmfsm_version_number_module} esmfsm_version_number)
endif()
if(NOT TARGET esmfsm_c)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${esmfsm_c_module} esmfsm_c)
endif()
if(NOT TARGET esmfsm)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${esmfsm_module} esmfsm)
endif()
if(NOT TARGET d_hydro_lib)
    add_subdirectory(${CMAKE_SOURCE_DIR}/src/${d_hydro_lib_module} d_hydro_lib)
endif()

# Flow2d3d
# Include the flow2d3d components as last as it depends on the properties set in the other components
# Data needs to be loaded prior before the other flow2d3d modules as its include directory needs to be set
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_data_module} flow2d3d_data)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_plugin_culvert_c_module} flow2d3d_plugin_culvert_c)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_plugin_user_module} flow2d3d_plugin_user)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_io_dol_f_module} flow2d3d_io_dol_f)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_io_module} flow2d3d_io)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_kernel_dd_f_module} flow2d3d_kernel_dd_f)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_kernel_module} flow2d3d_kernel)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_manager_module} flow2d3d_manager)
add_subdirectory(${CMAKE_SOURCE_DIR}/src/${flow2d3d_module} flow2d3d)

# Project name must be at the end of the configuration: it might get a name when including other configurations and needs to overwrite that
project(flow2d3d)
