SUBROUTINE PNPOLY(PX,PY,XX,YY,N,INOUT) 
REAL X(200),Y(200),XX(N),YY(N) 
REAL TMP
LOGICAL MX,MY,NX,NY 
MAXDIM=200 

IF(N>MAXDIM)THEN
  WRITE(*,*) 'WARNING:',N,' TOO GREAT FOR THIS VERSION OF PNPOLY.  RESULTS INVALID' 
  RETURN 
ENDIF

DO I=1,N 
  X(I)=XX(I)-PX 
  Y(I)=YY(I)-PY 
ENDDO

INOUT=-1 
DO I=1,N 
   J=1+MOD(I,N) 
   MX=X(I).GE.0.0 
   NX=X(J).GE.0.0 
   MY=Y(I).GE.0.0 
   NY=Y(J).GE.0.0 
   IF(.NOT.((MY.OR.NY).AND.(MX.OR.NX)).OR.(MX.AND.NX)) CYCLE
   IF (MY.AND.NY.AND.(MX.OR.NX).AND..NOT.(MX.AND.NX)) THEN
     INOUT=-INOUT 
     CYCLE
   ENDIF
   TMP = (Y(I)*X(J)-X(I)*Y(J))/(X(J)-X(I))
   IF(TMP<0.0) THEN
     ! JUST CONTINUE
   ELSEIF (TMP>0.0) THEN
     INOUT=-INOUT 
   ELSE
     ! on line
     INOUT=0 
     RETURN 
   ENDIF
ENDDO
end subroutine PNPOLY
